name: project_uav
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9.*
  - pip

  - pytorch 
  - torchvision 
  - pytorch-cuda=11.8
  - Cython
  - tqdm
  - PyYAML
  - matplotlib
  - numpy 
  - Pillow
  - opencv
  - scipy
  - numba
  - pathlib
  - streamlit
  - fastapi
  - uvicorn-standard

  # dev utility packages
  - ipykernel
  - ipywidgets


